# Write a python program to display IMDB’s Top rated 100 Indian movies’ data
# https://www.imdb.com/list/ls056092300/ (i.e. name, rating, year ofrelease) and make data frame.

In [4]:
from bs4 import BeautifulSoup
import requests
import random
import pandas as pd
import regex as re

In [5]:
url_1=requests.get('https://www.imdb.com/list/ls056092300/')
url_1

In [6]:
soup_1=BeautifulSoup(url_1.content)
soup_1

<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
</body>
</html>

In [7]:
userAgents=[
'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36',
'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36',
'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0. 1587.50',
'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36',
'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 OPR/94.0.0.0'
]

In [8]:
url_1=requests.get('https://www.imdb.com/list/ls056092300/',headers={'User-Agent':random.choice(userAgents)})
url_1

In [9]:
soup_1=BeautifulSoup(url_1.content)

In [27]:
name=soup_1.find('h3',class_="ipc-title__text")
print(name.text)


rating=soup_1.find('span',class_="ipc-rating-star--rating")
print(rating.text)

YPR=soup_1.find('span',class_="sc-b189961a-8 hCbzGp dli-title-metadata-item")
print(YPR.text)

1. Ship of Theseus
8.0
2012

In [105]:
#Extracting all the name from the given website
title_names=[]

for i in soup_1.find_all('h3',class_="ipc-title__text"):
    title_names.append(i.text)
print('-' * 127) 
print('Title Names')
print(title_names)
print('-' * 127)
#title name contains number as well Eg:'1. Ship of Theseus' and also we had unwanted data at the end, 
#so by the below code we can extract only the movies name's as we required.

name=[]

for i in title_names:
    p=re.compile('\A[0-9.]+')
    m=re.sub(p,"",i)
    name.append(m)
    
#Created a series 
Name=pd.Series(name[:-2])
print('-' * 127) 
print(Name)
print('-' * 127) 

#Below code is used to extracting all the Rating from the given website

title_rating=[]
for i in soup_1.find_all('span',class_="ipc-rating-star--rating"):
    title_rating.append(i.text)

print('-' * 127) 
print(title_rating)
print('-' * 127)
    

#Below code is used to extracting all the Year of release from the given website

title_year=[]

for i in soup_1.find_all('div',class_="sc-b189961a-7 btCcOY dli-title-metadata"):
    title_year.append(i.text)

print('-' * 127) 
print(title_year)# As the findall function find all the data which also contains year and time ,so further we will extract data as required 
print('-' * 127)

year_of_release=[]

for i in title_year:
    p=re.compile('[0-9][0-9][0-9][0-9]')
    m=re.findall(p,i)
    year_of_release.append(m)
    
print('-' * 127) 
print(year_of_release)
print('-' * 127)


IMDB=pd.DataFrame({'Name':Name,'Rating':title_rating,'Year_of_Release':year_of_release})
IMDB

-------------------------------------------------------------------------------------------------------------------------------
Title Names
['1. Ship of Theseus', '2. Iruvar', '3. Kaagaz Ke Phool', '4. Lagaan: Once Upon a Time in India', '5. Pather Panchali', '6. Charulata', '7. Rang De Basanti', '8. Dev.D', '9. 3 Idiots', '10. Awaara', '11. Nayakan', '12. Aparajito', '13. Pushpaka Vimana', '14. Pyaasa', '15. Ghatashraddha', '16. Sholay', '17. Aradhana', '18. Do Ankhen Barah Haath', '19. Bombay', '20. Neecha Nagar', '21. Do Bigha Zamin', '22. Garm Hava', '23. Piravi', '24. Mughal-E-Azam', '25. Amma Ariyan', 'More to explore', 'Recently viewed']
-------------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------------
0                        Ship of Theseus
1                                 Iruvar
2                        Kaagaz Ke Phool
3      Lagaan: Once Upon a Time in India
4                        Pather Panchali
5                              Charulata
6                        Rang De Basanti
7                                  Dev.D
8                               3 Idiots
9                                 Awaara
10                               Nayakan
11                             Aparajito
12                       Pushpaka Vimana
13                                Pyaasa
14                         Ghatashraddha
15                                Sholay
16                              Aradhana
17                 Do Ankhen Barah Haath
18                                Bombay
19                          Neecha Nagar
20                        Do Bigha Zamin
21                             Garm Hava
22                                Piravi
23                         Mughal-E-Azam
24                           Amma Ariyan
dtype: object
-------------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------------
['8.0', '8.4', '7.8', '8.1', '8.2', '8.1', '8.1', '7.9', '8.4', '7.8', '8.7', '8.2', '8.6', '8.3', '7.5', '8.1', '7.6', '8.4', '8.1', '6.6', '8.3', '8.0', '7.8', '8.1', '7.4']
-------------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------------
['20122h 19mUA', '19972h 20mUA', '19592h 28mU', '20013h 44mU', '19552h 5mU', '19641h 57mU', '20062h 47mUA', '20092h 24mA', '20092h 50mUA', '19513h 13mU', '19872h 36mA', '19561h 50mU', '19872h 5mU', '19572h 26mU', '19772h 24mA', '19753h 24mU', '19692h 49mU', '19572h 23mU', '19952h 21mU', '19462h 2mU', '19532h 11mU', '19742h 26m(Banned)', '19891h 50mUnrated', '19603h 17mPG', '19861h 55m']
-------------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------------
[['2012'], ['1997'], ['1959'], ['2001'], ['1955'], ['1964'], ['2006'], ['2009'], ['2009'], ['1951'], ['1987'], ['1956'], ['1987'], ['1957'], ['1977'], ['1975'], ['1969'], ['1957'], ['1995'], ['1946'], ['1953'], ['1974'], ['1989'], ['1960'], ['1986']]
-------------------------------------------------------------------------------------------------------------------------------

                                  Name Rating Year_of_Release
0                      Ship of Theseus    8.0          [2012]
1                               Iruvar    8.4          [1997]
2                      Kaagaz Ke Phool    7.8          [1959]
3    Lagaan: Once Upon a Time in India    8.1          [2001]
4                      Pather Panchali    8.2          [1955]
5                            Charulata    8.1          [1964]
6                      Rang De Basanti    8.1          [2006]
7                                Dev.D    7.9          [2009]
8                             3 Idiots    8.4          [2009]
9                               Awaara    7.8          [1951]
10                             Nayakan    8.7          [1987]
11                           Aparajito    8.2          [1956]
12                     Pushpaka Vimana    8.6          [1987]
13                              Pyaasa    8.3          [1957]
14                       Ghatashraddha    7.5          [1977]
15                              Sholay    8.1          [1975]
16                            Aradhana    7.6          [1969]
17               Do Ankhen Barah Haath    8.4          [1957]
18                              Bombay    8.1          [1995]
19                        Neecha Nagar    6.6          [1946]
20                      Do Bigha Zamin    8.3          [1953]
21                           Garm Hava    8.0          [1974]
22                              Piravi    7.8          [1989]
23                       Mughal-E-Azam    8.1          [1960]
24                         Amma Ariyan    7.4          [1986]

# Write a python program to scrape house details from mentioned URL. It should include house title, location,area, EMI and price from https://www.nobroker.in/ .Enter three localities which are Indira Nagar, Jayanagar,Rajaji Nagar.

In [10]:
url_2=requests.get('https://www.nobroker.in/property/sale/bangalore/multiple?searchParam=W3sibGF0IjoxMi45NzgzNjkyLCJsb24iOjc3LjY0MDgzNTYsInBsYWNlSWQiOiJDaElKa1FOM0dLUVdyanNSTmhCUUpyaEdEN1UiLCJwbGFjZU5hbWUiOiJJbmRpcmFuYWdhciJ9LHsibGF0IjoxMi45MzA3NzM1LCJsb24iOjc3LjU4MzgzMDIsInBsYWNlSWQiOiJDaElKMmRkbFo1Z1ZyanNSaDFCT0FhZi1vcnMiLCJwbGFjZU5hbWUiOiJKYXlhbmFnYXIifSx7ImxhdCI6MTIuOTk4MTczMiwibG9uIjo3Ny41NTMwNDQ1OTk5OTk5OSwicGxhY2VJZCI6IkNoSUp4Zlc0RFBNOXJqc1JLc05URy01cF9RUSIsInBsYWNlTmFtZSI6IlJhamFqaW5hZ2FyIn1d&radius=2.0&city=bangalore&locality=Indiranagar,Jayanagar,Rajajinagar')
url_2

In [11]:
soup_2=BeautifulSoup(url_2.content)

In [17]:
house=soup_2.find('a',class_="overflow-hidden overflow-ellipsis whitespace-nowrap max-w-80pe po:max-w-full")
print(house.text)

title_location=soup_2.find('div',class_="mt-0.5p overflow-hidden overflow-ellipsis whitespace-nowrap max-w-70 text-gray-light leading-4 po:mb-0.1p po:max-w-95")
title_location.text


title_price=soup_2.find('div',class_="font-semi-bold heading-6")
print(title_price.text)

emi_1='Not under loan₹ ₹1.3 Crores₹3,939 per sq.ft.₹74,508/MonthEstimated EMI3,300 sqftBuiltup'

p=re.compile('\..\d+,\d+')
m=re.findall(p,emi_1)
m

4+ BHK House For Sale  In Rajajinagar
₹1.3 Crores

['.₹74,508']

In [442]:
title_house=[]

for i in soup_2.find_all('a',class_="overflow-hidden overflow-ellipsis whitespace-nowrap max-w-80pe po:max-w-full"):
    title_house.append(i.text)


print(pd.DataFrame(title_house))
print('-' * 125) 
print('-' * 125) 
          
# Extracting the first three words

house=[]

for s in title_house:
    pattern = re.compile(r"^([\w+]+\s[\w+]+\s[\w+]+)")
    matche_title_house = re.search(pattern, s).group(1) 
    house.append(matche_title_house)

House=pd.DataFrame(house,columns=['Title'])
print(House)
print('-' * 125) 
print('-' * 125) 

title_location=[]

for i in soup_2.find_all('div',class_="mt-0.5p overflow-hidden overflow-ellipsis whitespace-nowrap max-w-70 text-gray-light leading-4 po:mb-0.1p po:max-w-95"):
    title_location.append(i.text)
    
Loaction=pd.DataFrame(title_location,columns=['Location'])


print(Loaction)
print('-'*125)
print('-'*125)


title_area=[]

for i in title_house:
    p=re.compile(r'(\s\w+).+(\s\w+).+(\s\w+)')
    m=re.search(p,i).group(3)
    title_area.append(m)
    
Area=pd.DataFrame(title_area,columns=['Area'])
print(Area)
print('-'*125)
print('-'*125)


title_price=[]

for i in soup_2.find_all('div',class_="p-1.5p flex border-b border-b-solid border-cardbordercolor tp:py-1p tp:px-1.5p tp:border-b-0"):
    title_price.append(i.text)


price=pd.DataFrame(title_price)
price[0]=price[0].str.replace('₹', '')
print(price)
print('-'*125)
print('-'*125)

title_Price=[]

for i in price[0]:
    p1=re.compile(r'(([0-9].[0-9]\s)|(\d)+\s)[a-zA-Z]')
    m=re.search(p1,i)
    title_Price.append(m.group(0))



Price=pd.DataFrame(title_Price,columns=['Price'])

print(Price)
print('-'*125)
print('-'*125)

results_emi = []

pattern =re.compile( r"[\d,]+(?:\.\d+)?(?:\sLacs|\sCrores)?/MonthEstimated")

for text in title_price:
    matches = re.findall(pattern, text)
    for match in matches:
        results_emi.append(match)

        
EMI = pd.DataFrame(results_emi, columns=['Emi'])
print(EMI)
print('-'*125)
print('-'*125)

                                                    0
0               4+ BHK House For Sale  In Rajajinagar
1   2 BHK Flat In Sr Apartment For Sale  In Jayanagar
2                3 BHK House For Sale  In Rajajinagar
3   2 BHK Apartment In  Habitat For Sale  In Rajaj...
4   2 BHK Flat In Ramya Regent For Sale  In Indira...
5   3 BHK Flat In Prospera Cerscent For Sale  In I...
6   2 BHK Apartment In Uber Paxina, Jayanagar For ...
7   3 BHK Apartment In Comfort Crissa For Sale  In...
8   2 BHK Flat In Pinnacle Appartment For Sale  In...
9   2 BHK Flat In Monolithic Apartments For Sale  ...
10  2 BHK Apartment In Alpine Regency For Sale  In...
11             4+ BHK House For Sale  In Rajaji Nagar
12  4 BHK Apartment In Brigade Gateway For Sale  I...
13   2 BHK Flat In Syed Ghouse For Sale  In Jayanagar
14  2 BHK Flat In Blue Berry Apartment  For Sale  ...
15                  2 BHK Flat For Sale  In Jayanagar
16      3 BHK House For Sale  In Agrahara Dasarahalli
17  3 BHK Flat In Chithaary Heights For Sale  In B...
18  3 BHK Flat In Samrat Apartments For Sale  In J...
19  2 BHK Flat In South End Apartments, 73, Rv Roa...
20  2 BHK Flat In Pooja Residency For Sale  In Ind...
21    4+ BHK House For Sale  In Rajajinagar 3rd Block
22             4+ BHK House For Sale  In Indira Nagar
23  2 BHK Flat In Admiralty Manor For Sale  In Ind...
24  4+ BHK Apartment In Phoenix Kessaku For Sale  ...
25              4+ BHK House For Sale  In Rajajinagar
-----------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------
               Title
0       4+ BHK House
1         2 BHK Flat
2        3 BHK House
3    2 BHK Apartment
4         2 BHK Flat
5         3 BHK Flat
6    2 BHK Apartment
7    3 BHK Apartment
8         2 BHK Flat
9         2 BHK Flat
10   2 BHK Apartment
11      4+ BHK House
12   4 BHK Apartment
13        2 BHK Flat
14        2 BHK Flat
15        2 BHK Flat
16       3 BHK House
17        3 BHK Flat
18        3 BHK Flat
19        2 BHK Flat
20        2 BHK Flat
21      4+ BHK House
22      4+ BHK House
23        2 BHK Flat
24  4+ BHK Apartment
25      4+ BHK House
-----------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------
                                             Location
0   Independent House, 14th Main Rd near Athmeya p...
1                                     11th main cross
2   Independent House, Mahalaxmi Lyaout  near Path...
3    Habitat  14 th cross  1st block Rajajinagar b...
4                                near police station
5   9th Main Road, 80 Feet Rd, opp. Canara Bank, H...
6   Uber Paxina, Jayanagar   454, 7th Cross Rd, 6t...
7   Comfort Crissa  Comfort Crissa, 16th Cross Rd,...
8   Subramanyanagar near Sir M Visvesvaraya Co-ope...
9   Monolithic ApartmentsRajajinagar, 132/A, 3rd C...
10  Alpine Regency   Alpine Regency, 10th D Main R...
11  Independent House, Lakshminarayanapuram,  near...
12  Brigade Gateway  Brigade Gateway Resident Ln, ...
13         4th T Block East,Near Tilak English School
14  13th E Main Rd 8th cross, Paramahansa Yoganand...
15  Standalone Building, 22nd Cross Road, 3rd Bloc...
16  Independent House, near Shell petrol bunk and ...
17                               Jayanagar, Bangalore
18  East End D Main Rd, Jayanagar, 9th Block, Beng...
19                                  Kengeri Ring Road
20  Indira Nagar, HAL 2nd Stage, Bangalore, Karnat...
21  Independent House, Rajajinagar 3rd Block, Raja...
22  Independent House, Hal 2nd Stage near Dr. Ambe...
23  Admiralty Manor, 6th Main Rd, Eshwara Layout, ...
24  Phoenix Kessaku  Opp. Vivekananda College,Dr R...
25  Independent House, 14th Main Rd near Athmeya p...
-----------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------
             Area
0     Rajajinagar
1       Jayanagar
2     Rajajinagar
3     Rajajinagar
4     Indiranagar
5       Bangalore
6       Jayanagar
7    Doddanekundi
8     Rajajinagar
9        Nagapura
10      Jayanagar
11          Nagar
12    Rajajinagar
13      Jayanagar
14    Indiranagar
15      Jayanagar
16    Dasarahalli
17           Road
18      Jayanagar
19         Circle
20          Nagar
21          Block
22          Nagar
23    Indiranagar
24    Rajajinagar
25    Rajajinagar
-----------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------
                                                    0
0   Not under loan 1.3 Crores3,939 per sq.ft.74,50...
1   Not under loan 75 Lacs6,818 per sq.ft.42,985/M...
2   Not under loan 6.35 Crores31,750 per sq.ft.3.6...
3   Not under loan 87 Lacs7,909 per sq.ft.49,863/M...
4   Not under loan 1 Crore10,905 per sq.ft.57,314/...
5   Not under loan 1.9 Crores12,583 per sq.ft.1.09...
6   Not under loan 1.6 Crores12,976 per sq.ft.91,7...
7   Not under loan 70 Lacs5,385 per sq.ft.40,120/M...
8   Not under loan 1.15 Crores10,952 per sq.ft.65,...
9   Not under loan 49 Lacs7,313 per sq.ft.28,084/M...
10  Not under loan 1.65 Crores12,500 per sq.ft.94,...
11  Not under loan 4 Crores17,778 per sq.ft.2.29 L...
12  Under Loan 4.5 Crores19,565 per sq.ft.2.58 Lac...
13  Not under loan 38.5 Lacs6,417 per sq.ft.22,066...
14  Not under loan 1.25 Crores11,639 per sq.ft.71,...
15  Not under loan 58 Lacs7,250 per sq.ft.33,242/M...
16  Under Loan 1.25 Crores5,208 per sq.ft.71,643/M...
17  Not under loan 95 Lacs7,588 per sq.ft.54,448/M...
18  Not under loan 1.15 Crores8,042 per sq.ft.65,9...
19  Not under loan 95 Lacs11,875 per sq.ft.54,448/...
20  Not under loan 85 Lacs7,944 per sq.ft.48,717/M...
21  Not under loan 6.75 Crores15,341 per sq.ft.3.8...
22  Not under loan 11 Crores22,000 per sq.ft.6.3 L...
23  Not under loan 1.7 Crores14,592 per sq.ft.97,4...
24  Not under loan 11.18 Crores27,585 per sq.ft.6....
25  Not under loan 1.3 Crores3,939 per sq.ft.74,50...
-----------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------
    Price
0   1.3 C
1    75 L
2    35 C
3    87 L
4     1 C
5   1.9 C
6   1.6 C
7    70 L
8    15 C
9    49 L
10   65 C
11    4 C
12  4.5 C
13  8.5 L
14   25 C
15   58 L
16   25 C
17   95 L
18   15 C
19   95 L
20   85 L
21   75 C
22   11 C
23  1.7 C
24   18 C
25  1.3 C
-----------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------
                         Emi
0      74,508/MonthEstimated
1      42,985/MonthEstimated
2   3.64 Lacs/MonthEstimated
3      49,863/MonthEstimated
4      57,314/MonthEstimated
5   1.09 Lacs/MonthEstimated
6      91,703/MonthEstimated
7      40,120/MonthEstimated
8      65,911/MonthEstimated
9      28,084/MonthEstimated
10     94,568/MonthEstimated
11  2.29 Lacs/MonthEstimated
12  2.58 Lacs/MonthEstimated
13     22,066/MonthEstimated
14     71,643/MonthEstimated
15     33,242/MonthEstimated
16     71,643/MonthEstimated
17     54,448/MonthEstimated
18     65,911/MonthEstimated
19     54,448/MonthEstimated
20     48,717/MonthEstimated
21  3.87 Lacs/MonthEstimated
22   6.3 Lacs/MonthEstimated
23     97,434/MonthEstimated
24  6.41 Lacs/MonthEstimated
25     74,508/MonthEstimated
-----------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------

In [440]:
NO_Broker=pd.concat([House,Loaction,Area,Price,EMI],axis=1)
NO_Broker

,Title,Location,Area,Price,Emi
0,4+ BHK House,"Independent House, 14th Main Rd near Athmeya p...",Rajajinagar,1.3 C,"74,508/MonthEstimated"
1,2 BHK Flat,11th main cross,Jayanagar,75 L,"42,985/MonthEstimated"
2,3 BHK House,"Independent House, Mahalaxmi Lyaout near Path...",Rajajinagar,35 C,3.64 Lacs/MonthEstimated
3,2 BHK Apartment,Habitat 14 th cross 1st block Rajajinagar b...,Rajajinagar,87 L,"49,863/MonthEstimated"
4,2 BHK Flat,near police station,Indiranagar,1 C,"57,314/MonthEstimated"
5,3 BHK Flat,"9th Main Road, 80 Feet Rd, opp. Canara Bank, H...",Bangalore,1.9 C,1.09 Lacs/MonthEstimated
6,2 BHK Apartment,"Uber Paxina, Jayanagar 454, 7th Cross Rd, 6t...",Jayanagar,1.6 C,"91,703/MonthEstimated"
7,3 BHK Apartment,"Comfort Crissa Comfort Crissa, 16th Cross Rd,...",Doddanekundi,70 L,"40,120/MonthEstimated"
8,2 BHK Flat,Subramanyanagar near Sir M Visvesvaraya Co-ope...,Rajajinagar,15 C,"65,911/MonthEstimated"
9,2 BHK Flat,"Monolithic ApartmentsRajajinagar, 132/A, 3rd C...",Nagapura,49 L,"28,084/MonthEstimated"
10,2 BHK Apartment,"Alpine Regency Alpine Regency, 10th D Main R...",Jayanagar,65 C,"94,568/MonthEstimated"
11,4+ BHK House,"Independent House, Lakshminarayanapuram, near...",Nagar,4 C,2.29 Lacs/MonthEstimated
12,4 BHK Apartment,"Brigade Gateway Brigade Gateway Resident Ln, ...",Rajajinagar,4.5 C,2.58 Lacs/MonthEstimated
13,2 BHK Flat,"4th T Block East,Near Tilak English School",Jayanagar,8.5 L,"22,066/MonthEstimated"
14,2 BHK Flat,"13th E Main Rd 8th cross, Paramahansa Yoganand...",Indiranagar,25 C,"71,643/MonthEstimated"
15,2 BHK Flat,"Standalone Building, 22nd Cross Road, 3rd Bloc...",Jayanagar,58 L,"33,242/MonthEstimated"
16,3 BHK House,"Independent House, near Shell petrol bunk and ...",Dasarahalli,25 C,"71,643/MonthEstimated"
17,3 BHK Flat,"Jayanagar, Bangalore",Road,95 L,"54,448/MonthEstimated"
18,3 BHK Flat,"East End D Main Rd, Jayanagar, 9th Block, Beng...",Jayanagar,15 C,"65,911/MonthEstimated"
19,2 BHK Flat,Kengeri Ring Road,Circle,95 L,"54,448/MonthEstimated"
20,2 BHK Flat,"Indira Nagar, HAL 2nd Stage, Bangalore, Karnat...",Nagar,85 L,"48,717/MonthEstimated"
21,4+ BHK House,"Independent House, Rajajinagar 3rd Block, Raja...",Block,75 C,3.87 Lacs/MonthEstimated
22,4+ BHK House,"Independent House, Hal 2nd Stage near Dr. Ambe...",Nagar,11 C,6.3 Lacs/MonthEstimated
23,2 BHK Flat,"Admiralty Manor, 6th Main Rd, Eshwara Layout, ...",Indiranagar,1.7 C,"97,434/MonthEstimated"
24,4+ BHK Apartment,"Phoenix Kessaku Opp. Vivekananda College,Dr R...",Rajajinagar,18 C,6.41 Lacs/MonthEstimated
25,4+ BHK House,"Independent House, 14th Main Rd near Athmeya p...",Rajajinagar,1.3 C,"74,508/MonthEstimated"

# Write a python program to scrape first 10 product details which include product name , price , Image URL from https://www.bewakoof.com/bestseller?sort=popular

In [12]:
url_4=requests.get('https://www.bewakoof.com/bestseller?sort=popular%20')
url_4

In [13]:
soup_4=BeautifulSoup(url_4.content)

In [18]:
name=soup_4.find('div',class_="d-flex")
print(name.text)
price=soup_4.find('div',class_="discountedPriceText clr-p-black false")
print(price.text)
img=soup_4.find('div',class_="productImg")
img

bewakoof x dcMen's Black Adam Graphic Printed T-shirt
₹499

<div class="productImg" style="width:100%;padding-top:135%;position:relative;background:rgb(245, 247, 246)"><img alt="Shop Men's Black Adam Graphic Printed T-shirt-Front" class="productImgTag" decoding="async" height="100%" loading="lazy" src="https://images.bewakoof.com/t640/men-s-black-adam-graphic-printed-t-shirt-541266-1709214736-1.jpg" title="Men's Black Adam Graphic Printed T-shirt-Front Bewakoof" width="100%"/></div>

In [451]:
title_name=[]

for i in soup_4.find_all('div',class_="productNaming bkf-ellipsis"):
    title_name.append(i.text)
    
Name=pd.DataFrame(title_name,columns=['Product'])
print(Name)
print('-'*125)
print('-'*125)

title_price=[]

for i in soup_4.find_all('div',class_="discountedPriceText clr-p-black false"):
    title_price.append(i.text)
    
Price=pd.DataFrame(title_price,columns=['Price'])
print(Price)
print('-'*125)
print('-'*125)


title_img = []

for i in soup_4.find_all('img',class_="productImgTag"):
    # Try to get 'data-src', fallback to 'src' if 'data-src' doesn't exist
    img_url = i.get('data-src') or i.get('src')
    if img_url:
        title_img.append(img_url)

Img=pd.DataFrame(title_img,columns=['Image'])
print(Img)
print('-'*125)
print('-'*125)

                                             Product
0  bewakoof x dcMen's Black Adam Graphic Printed ...
1  Bewakoof®Men's Black Warriors Graphic Printed ...
2  bewakoof x house of the dragonMen's Black Hous...
3  bewakoof x tom & jerryWomen's Blue Moody Jerry...
4  Bewakoof®Women's Black Anti Hero Graphic Print...
5  Bewakoof®Women's White & Purple Camo Printed O...
6       Bewakoof®Men's White Wander Geometry T-shirt
7  bewakoof x tom & jerryWomen's Green Weirdos Fo...
8  Bewakoof®Men's Blue Rider Vroom Panda Graphic ...
9  bewakoof x rick and mortyMen's Green Stoned Ri...
-----------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------
  Price
0  ₹499
1  ₹499
2  ₹399
3  ₹499
4  ₹499
5  ₹439
6  ₹499
7  ₹499
8  ₹499
9  ₹499
-----------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------
                                               Image
0  https://images.bewakoof.com/t640/men-s-black-a...
1  https://images.bewakoof.com/t640/men-s-black-w...
2  https://images.bewakoof.com/t640/men-s-black-h...
3  https://images.bewakoof.com/t640/women-s-blue-...
4  https://images.bewakoof.com/t640/women-s-black...
5  https://images.bewakoof.com/t640/women-aop-ove...
6  https://images.bewakoof.com/t640/men-s-white-w...
7  https://images.bewakoof.com/t640/women-s-green...
8  https://images.bewakoof.com/t640/men-s-blue-ri...
9  https://images.bewakoof.com/t640/men-s-green-s...
-----------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------

In [452]:
bewakoof=pd.concat([Name,Price,Img],axis=1)
bewakoof

,Product,Price,Image
0,bewakoof x dcMen's Black Adam Graphic Printed ...,₹499,https://images.bewakoof.com/t640/men-s-black-a...
1,Bewakoof®Men's Black Warriors Graphic Printed ...,₹499,https://images.bewakoof.com/t640/men-s-black-w...
2,bewakoof x house of the dragonMen's Black Hous...,₹399,https://images.bewakoof.com/t640/men-s-black-h...
3,bewakoof x tom & jerryWomen's Blue Moody Jerry...,₹499,https://images.bewakoof.com/t640/women-s-blue-...
4,Bewakoof®Women's Black Anti Hero Graphic Print...,₹499,https://images.bewakoof.com/t640/women-s-black...
5,Bewakoof®Women's White & Purple Camo Printed O...,₹439,https://images.bewakoof.com/t640/women-aop-ove...
6,Bewakoof®Men's White Wander Geometry T-shirt,₹499,https://images.bewakoof.com/t640/men-s-white-w...
7,bewakoof x tom & jerryWomen's Green Weirdos Fo...,₹499,https://images.bewakoof.com/t640/women-s-green...
8,Bewakoof®Men's Blue Rider Vroom Panda Graphic ...,₹499,https://images.bewakoof.com/t640/men-s-blue-ri...
9,bewakoof x rick and mortyMen's Green Stoned Ri...,₹499,https://images.bewakoof.com/t640/men-s-green-s...

# scrap 'https://www.cnbc.com/economy/' a)headings b) date c) News link

In [19]:
ulr_q5=requests.get('https://www.cnbc.com/economy/')
ulr_q5

In [21]:
soup_q5=BeautifulSoup(ulr_q5.content)

In [22]:
title_heading=soup_q5.find('a',class_="Card-title")
print(title_heading.text)

title_date=soup_q5.find('span',class_="Card-time")
print(title_date.text)

Europe's economy survived 'terrible prophecies' but must now tackle trade with China: EU's Gentiloni
Sat, Sep 7th 2024

In [463]:
title_h=[]

for i in soup_q5.find_all('a',class_="Card-title"):
    title_h.append(i.text)
Heading=pd.DataFrame(title_h,columns=['Heading'])

print(Heading)
print('-'*125)
print('-'*125)


title_d=[]

for i in soup_q5.find_all('span',class_="Card-time"):
    title_d.append(i.text)
Date=pd.DataFrame(title_d,columns=['Date'])
print(Date)
print('-'*125)
print('-'*125)


articles = soup_q5.find_all('div', class_='Card-titleContainer')

title_articles=[]
for article in articles:
    link = article.find('a')['href']
    title_articles.append(link)

Links=pd.DataFrame(title_articles,columns=['Links'])
Links

                                              Heading
0   Europe's economy survived 'terrible prophecies...
1   Unemployment rate for Black workers falls in A...
2   Fed Governor Waller backs interest rate cut at...
3   Here's where the jobs are for August 2024 — in...
4   August payrolls grew by just 142,000, but unem...
5   Friday's jobs report for August is going to be...
6   Private payrolls rose by 99,000 in August, low...
7   Layoffs jump in August while hiring in 2024 is...
8   Bond market 'yield curve' returns to normal fr...
9   Job openings fell more than expected in July i...
10  Atlanta Fed's Bostic says officials can't wait...
11  Weak manufacturing measures raise specter of U...
12  The Fed’s favorite inflation indicator increas...
13  Euro zone inflation falls to 3-year low of 2.2...
14  The Fed's preferred inflation indicator is out...
15  The Fed now will focus on the employment part ...
16  Increased sausage demand could be worrying sig...
17  Markets are now wondering whether the Fed migh...
18  Saudi Arabia’s spending and investments confir...
19  A recession is coming in the U.S., and 'a few ...
20  Jobs growth gets its biggest downward revision...
21  Nonfarm payroll growth revised down by 818,000...
22  Fed survey shows lows in employment, worries a...
23  Goldman Sachs cuts odds of U.S. recession to 2...
24  Egg prices are rising once again as bird flu l...
25  How a week's worth of huge economic news will ...
26  Consumer spending jumped in July as retail sal...
27  UK economy expands 0.6% in second quarter; Jun...
28  Annual inflation rate slows to 2.9% in July, l...
29  Wednesday's big CPI inflation report could mar...
30  Wholesale inflation measure rose 0.1% in July,...
31  Three-year inflation outlook hits record low i...
32  Inflation spike in Europe is tied to the Olymp...
33  Jeremy Siegel backs off on calls for the Fed t...
-----------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------
                  Date
0    Sat, Sep 7th 2024
1    Fri, Sep 6th 2024
2    Fri, Sep 6th 2024
3    Fri, Sep 6th 2024
4    Fri, Sep 6th 2024
5    Fri, Sep 6th 2024
6    Thu, Sep 5th 2024
7    Thu, Sep 5th 2024
8    Wed, Sep 4th 2024
9    Wed, Sep 4th 2024
10   Wed, Sep 4th 2024
11   Tue, Sep 3rd 2024
12  Fri, Aug 30th 2024
13  Fri, Aug 30th 2024
14  Thu, Aug 29th 2024
15  Wed, Aug 28th 2024
16  Mon, Aug 26th 2024
17  Fri, Aug 23rd 2024
18  Fri, Aug 23rd 2024
19  Thu, Aug 22nd 2024
20  Wed, Aug 21st 2024
21  Wed, Aug 21st 2024
22  Mon, Aug 19th 2024
23  Mon, Aug 19th 2024
24  Mon, Aug 19th 2024
25  Sat, Aug 17th 2024
26  Thu, Aug 15th 2024
27  Thu, Aug 15th 2024
28  Wed, Aug 14th 2024
29  Wed, Aug 14th 2024
30  Tue, Aug 13th 2024
31  Mon, Aug 12th 2024
32  Sun, Aug 11th 2024
33   Fri, Aug 9th 2024
-----------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------

                                                Links
0   https://www.cnbc.com/2024/09/07/eu-economy-sur...
1   https://www.cnbc.com/2024/09/06/unemployment-a...
2   https://www.cnbc.com/2024/09/06/fed-governor-w...
3   https://www.cnbc.com/2024/09/06/heres-where-th...
4   https://www.cnbc.com/2024/09/06/jobs-report-au...
5   https://www.cnbc.com/2024/09/05/fridays-jobs-r...
6   https://www.cnbc.com/2024/09/05/august-private...
7   https://www.cnbc.com/2024/09/05/layoffs-jump-i...
8   https://www.cnbc.com/2024/09/04/bond-market-yi...
9   https://www.cnbc.com/2024/09/04/jolts-july-202...
10  https://www.cnbc.com/2024/09/04/atlanta-fed-pr...
11  https://www.cnbc.com/2024/09/03/weak-manufactu...
12  https://www.cnbc.com/2024/08/30/pce-inflation-...
13  https://www.cnbc.com/2024/08/30/euro-zone-infl...
14  https://www.cnbc.com/2024/08/29/the-feds-prefe...
15  https://www.cnbc.com/2024/08/28/the-fed-now-wi...
16  https://www.cnbc.com/2024/08/26/increased-saus...
17  https://www.cnbc.com/2024/08/23/markets-now-wo...
18  https://www.cnbc.com/2024/08/23/saudi-arabias-...
19  https://www.cnbc.com/2024/08/23/us-recession-i...
20  https://www.cnbc.com/2024/08/21/us-job-growth-...
21  https://www.cnbc.com/2024/08/21/nonfarm-payrol...
22  https://www.cnbc.com/2024/08/19/fed-survey-sho...
23  https://www.cnbc.com/2024/08/19/goldman-sachs-...
24  https://www.cnbc.com/2024/08/17/egg-prices-are...
25  https://www.cnbc.com/2024/08/17/how-a-weeks-hu...
26  https://www.cnbc.com/2024/08/15/retail-sales-j...
27  https://www.cnbc.com/2024/08/15/uk-second-quar...
28  https://www.cnbc.com/2024/08/14/july-consumer-...
29  https://www.cnbc.com/2024/08/13/wednesdays-cpi...
30  https://www.cnbc.com/2024/08/13/producer-price...
31  https://www.cnbc.com/2024/08/12/three-year-inf...
32  https://www.cnbc.com/2024/08/11/inflation-spik...
33  https://www.cnbc.com/2024/08/08/jeremy-siegel-...

In [464]:
CNBC=pd.concat([Heading,Date,Links],axis=1)
CNBC

,Heading,Date,Links
0,Europe's economy survived 'terrible prophecies...,"Sat, Sep 7th 2024",https://www.cnbc.com/2024/09/07/eu-economy-sur...
1,Unemployment rate for Black workers falls in A...,"Fri, Sep 6th 2024",https://www.cnbc.com/2024/09/06/unemployment-a...
2,Fed Governor Waller backs interest rate cut at...,"Fri, Sep 6th 2024",https://www.cnbc.com/2024/09/06/fed-governor-w...
3,Here's where the jobs are for August 2024 — in...,"Fri, Sep 6th 2024",https://www.cnbc.com/2024/09/06/heres-where-th...
4,"August payrolls grew by just 142,000, but unem...","Fri, Sep 6th 2024",https://www.cnbc.com/2024/09/06/jobs-report-au...
5,Friday's jobs report for August is going to be...,"Fri, Sep 6th 2024",https://www.cnbc.com/2024/09/05/fridays-jobs-r...
6,"Private payrolls rose by 99,000 in August, low...","Thu, Sep 5th 2024",https://www.cnbc.com/2024/09/05/august-private...
7,Layoffs jump in August while hiring in 2024 is...,"Thu, Sep 5th 2024",https://www.cnbc.com/2024/09/05/layoffs-jump-i...
8,Bond market 'yield curve' returns to normal fr...,"Wed, Sep 4th 2024",https://www.cnbc.com/2024/09/04/bond-market-yi...
9,Job openings fell more than expected in July i...,"Wed, Sep 4th 2024",https://www.cnbc.com/2024/09/04/jolts-july-202...
10,Atlanta Fed's Bostic says officials can't wait...,"Wed, Sep 4th 2024",https://www.cnbc.com/2024/09/04/atlanta-fed-pr...
11,Weak manufacturing measures raise specter of U...,"Tue, Sep 3rd 2024",https://www.cnbc.com/2024/09/03/weak-manufactu...
12,The Fed’s favorite inflation indicator increas...,"Fri, Aug 30th 2024",https://www.cnbc.com/2024/08/30/pce-inflation-...
13,Euro zone inflation falls to 3-year low of 2.2...,"Fri, Aug 30th 2024",https://www.cnbc.com/2024/08/30/euro-zone-infl...
14,The Fed's preferred inflation indicator is out...,"Thu, Aug 29th 2024",https://www.cnbc.com/2024/08/29/the-feds-prefe...
15,The Fed now will focus on the employment part ...,"Wed, Aug 28th 2024",https://www.cnbc.com/2024/08/28/the-fed-now-wi...
16,Increased sausage demand could be worrying sig...,"Mon, Aug 26th 2024",https://www.cnbc.com/2024/08/26/increased-saus...
17,Markets are now wondering whether the Fed migh...,"Fri, Aug 23rd 2024",https://www.cnbc.com/2024/08/23/markets-now-wo...
18,Saudi Arabia’s spending and investments confir...,"Fri, Aug 23rd 2024",https://www.cnbc.com/2024/08/23/saudi-arabias-...
19,"A recession is coming in the U.S., and 'a few ...","Thu, Aug 22nd 2024",https://www.cnbc.com/2024/08/23/us-recession-i...
20,Jobs growth gets its biggest downward revision...,"Wed, Aug 21st 2024",https://www.cnbc.com/2024/08/21/us-job-growth-...
21,"Nonfarm payroll growth revised down by 818,000...","Wed, Aug 21st 2024",https://www.cnbc.com/2024/08/21/nonfarm-payrol...
22,"Fed survey shows lows in employment, worries a...","Mon, Aug 19th 2024",https://www.cnbc.com/2024/08/19/fed-survey-sho...
23,Goldman Sachs cuts odds of U.S. recession to 2...,"Mon, Aug 19th 2024",https://www.cnbc.com/2024/08/19/goldman-sachs-...
24,Egg prices are rising once again as bird flu l...,"Mon, Aug 19th 2024",https://www.cnbc.com/2024/08/17/egg-prices-are...
25,How a week's worth of huge economic news will ...,"Sat, Aug 17th 2024",https://www.cnbc.com/2024/08/17/how-a-weeks-hu...
26,Consumer spending jumped in July as retail sal...,"Thu, Aug 15th 2024",https://www.cnbc.com/2024/08/15/retail-sales-j...
27,UK economy expands 0.6% in second quarter; Jun...,"Thu, Aug 15th 2024",https://www.cnbc.com/2024/08/15/uk-second-quar...
28,"Annual inflation rate slows to 2.9% in July, l...","Wed, Aug 14th 2024",https://www.cnbc.com/2024/08/14/july-consumer-...
29,Wednesday's big CPI inflation report could mar...,"Wed, Aug 14th 2024",https://www.cnbc.com/2024/08/13/wednesdays-cpi...
30,"Wholesale inflation measure rose 0.1% in July,...","Tue, Aug 13th 2024",https://www.cnbc.com/2024/08/13/producer-price...
31,Three-year inflation outlook hits record low i...,"Mon, Aug 12th 2024",https://www.cnbc.com/2024/08/12/three-year-inf...
32,Inflation spike in Europe is tied to the Olymp...,"Sun, Aug 11th 2024",https://www.cnbc.com/2024/08/11/inflation-spik...
33,Jeremy Siegel backs off on calls for the Fed t...,"Fri, Aug 9th 2024",https://www.cnbc.com/2024/08/08/jeremy-siegel-...

# visit https://www.keaipublishing.com/en/journals/artificial-intelligence-in-agriculture/most-downloadedarticles/and scrap a)Paper title b) date c) Author

In [23]:
url_6=requests.get('https://www.keaipublishing.com/en/journals/artificial-intelligence-in-agriculture/most-downloaded-articles/')
url_6

In [24]:
soup_6=BeautifulSoup(url_6.content)

In [28]:
title_paper=soup_6.find('div',class_="article-listing")
print(title_paper.text)

p='Implementation of artificial intelligence in agriculture for optimisation of irrigation and application of pesticides and herbicides\r\n                \n\n2020\n Tanha Talaviya |  Dhara Shah |  Nivedita Patel |  Hiteshri Yagnik |  Manan Shah\nAgriculture plays a significant role in the economic sector. The automation in agriculture is the main concern and the emerging subject across the world. The population is increasing tremendously and...\n'
patter_d=re.compile('[0-9][0-9][0-9][0-9]')
match_d=re.findall(patter_d,p)
print(match_d)

authors=soup_6.find('p',class_="article-authors")
print(authors.text)

                    Implementation of artificial intelligence in agriculture for optimisation of irrigation and application of pesticides and herbicides


2020
 Tanha Talaviya |  Dhara Shah |  Nivedita Patel |  Hiteshri Yagnik |  Manan Shah
Agriculture plays a significant role in the economic sector. The automation in agriculture is the main concern and the emerging subject across the world. The population is increasing tremendously and...

['2020']
 Tanha Talaviya |  Dhara Shah |  Nivedita Patel |  Hiteshri Yagnik |  Manan Shah

In [487]:
title_name=[]

for i in soup_6.find_all('div',class_="article-listing"):
    title_name.append(i.text)
title_name


title_Name=[]

for i in title_name:
    pattern= re.compile(r'(?:\n.*?){3}(.*?)\r')
    match=re.findall(pattern,i)
    title_Name.extend(match)

Clean_title_name=[m.strip() for m in f]
Title=pd.DataFrame(Clean_title_name,columns=['Titles'])
print(Title)
print('-'*125)
print('-'*125)

title_date=[]

for i in title_name:
    pattern_d=re.compile('[0-9][0-9][0-9][0-9]')
    match_d=re.findall(pattern_d,i)
    title_date.extend(match_d)
    
Date=pd.DataFrame(title_date,columns=['Date'])
print(Date)
print('-'*125)
print('-'*125)


title_authors=[]

for i in soup_6.find_all('p',class_="article-authors"):
    title_authors.append(i.text)
Authors=pd.DataFrame(title_authors,columns=['Authors'])
print(Authors)
print('-'*125)
print('-'*125)

                                               Titles
0   Implementation of artificial intelligence in a...
1               Review of agricultural IoT technology
2   Automation and digitization of agriculture usi...
3   A comprehensive review on automation in agricu...
4   Applications of electronic nose (e-nose) and e...
5   Towards sustainable agriculture: Harnessing AI...
6             Fruit ripeness classification: A survey
7   Deep learning based computer vision approaches...
8   A review of imaging techniques for plant disea...
9   Transfer Learning for Multi-Crop Leaf Disease ...
10  Comparison of CNN-based deep learning architec...
11  DeepRice: A deep learning and deep feature bas...
12  Computer vision in smart agriculture and preci...
13  Image classification on smart agriculture plat...
14  Using an improved lightweight YOLOv8 model for...
15  How artificial intelligence uses to achieve th...
16  LeafSpotNet: A deep learning framework for det...
17  Plant disease detection using hybrid model bas...
18  Cross-comparative review of Machine learning f...
19  A comprehensive survey on weed and crop classi...
20  A systematic review of machine learning techni...
21  Machine learning in nutrient management: A review
22  Deep convolutional neural network models for w...
23  A review on computer vision systems in monitor...
24  Explainable artificial intelligence and interp...
-----------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------
    Date
0   2020
1   2022
2   2021
3   2019
4   2020
5   2024
6   2023
7   2022
8   2020
9   2022
10  2023
11  2024
12  2024
13  2024
14  2024
15  2023
16  2024
17  2021
18  2024
19  2024
20  2022
21  2023
22  2022
23  2020
24  2022
-----------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------
                                              Authors
0    Tanha Talaviya |  Dhara Shah |  Nivedita Pate...
1          Jinyuan Xu |  Baoxing Gu |  Guangzhao Tian
2                            A. Subeesh |  C.R. Mehta
3    Kirtan Jha |  Aalap Doshi |  Poojan Patel |  ...
4                               Juzhong Tan |  Jie Xu
5                 Dhananjay K. Pandey |  Richa Mishra
6    Matteo Rizzo |  Matteo Marcuzzo |  Alessandro...
7    V.G. Dhanya |  A. Subeesh |  N.L. Kushwaha | ...
8        Vijai Singh |  Namita Sharma |  Shikha Singh
9              Ananda S. Paymode |  Vandana B. Malode
10   Md Taimur Ahad |  Yan Li |  Bo Song |  Touhid...
11   P. Isaac Ritharson |  Kumudha Raimond |  X. A...
12   Sumaira Ghazal |  Arslan Munir |  Waqar S. Qu...
13   Juan Felipe Restrepo-Arias |  John W. Branch-...
14   Baoling Ma |  Zhixin Hua |  Yuchen Wen |  Hon...
15            Vilani Sachithra |  L.D.C.S. Subhashini
16         Shwetha V |  Arnav Bhagwat |  Vijaya Laxmi
17                         Punam Bedi |  Pushkar Gole
18   James Daniel Omaye |  Emeka Ogbuju |  Grace A...
19   Faisal Dharma Adhinata |   Wahyono |  Raden S...
20   Md Ekramul Hossain |  Muhammad Ashad Kabir | ...
21   Oumnia Ennaji |  Leonardus Vergütz |  Achraf ...
22   A. Subeesh |  S. Bhole |  K. Singh |  N.S. Ch...
23   Cedric Okinda |  Innocent Nyalala |  Tchalla ...
24                                       Masahiro Ryo
-----------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------

In [488]:
KeAi=pd.concat([Title,Date,Authors],axis=1)
KeAi

,Titles,Date,Authors
0,Implementation of artificial intelligence in a...,2020,Tanha Talaviya | Dhara Shah | Nivedita Pate...
1,Review of agricultural IoT technology,2022,Jinyuan Xu | Baoxing Gu | Guangzhao Tian
2,Automation and digitization of agriculture usi...,2021,A. Subeesh | C.R. Mehta
3,A comprehensive review on automation in agricu...,2019,Kirtan Jha | Aalap Doshi | Poojan Patel | ...
4,Applications of electronic nose (e-nose) and e...,2020,Juzhong Tan | Jie Xu
5,Towards sustainable agriculture: Harnessing AI...,2024,Dhananjay K. Pandey | Richa Mishra
6,Fruit ripeness classification: A survey,2023,Matteo Rizzo | Matteo Marcuzzo | Alessandro...
7,Deep learning based computer vision approaches...,2022,V.G. Dhanya | A. Subeesh | N.L. Kushwaha | ...
8,A review of imaging techniques for plant disea...,2020,Vijai Singh | Namita Sharma | Shikha Singh
9,Transfer Learning for Multi-Crop Leaf Disease ...,2022,Ananda S. Paymode | Vandana B. Malode
10,Comparison of CNN-based deep learning architec...,2023,Md Taimur Ahad | Yan Li | Bo Song | Touhid...
11,DeepRice: A deep learning and deep feature bas...,2024,P. Isaac Ritharson | Kumudha Raimond | X. A...
12,Computer vision in smart agriculture and preci...,2024,Sumaira Ghazal | Arslan Munir | Waqar S. Qu...
13,Image classification on smart agriculture plat...,2024,Juan Felipe Restrepo-Arias | John W. Branch-...
14,Using an improved lightweight YOLOv8 model for...,2024,Baoling Ma | Zhixin Hua | Yuchen Wen | Hon...
15,How artificial intelligence uses to achieve th...,2023,Vilani Sachithra | L.D.C.S. Subhashini
16,LeafSpotNet: A deep learning framework for det...,2024,Shwetha V | Arnav Bhagwat | Vijaya Laxmi
17,Plant disease detection using hybrid model bas...,2021,Punam Bedi | Pushkar Gole
18,Cross-comparative review of Machine learning f...,2024,James Daniel Omaye | Emeka Ogbuju | Grace A...
19,A comprehensive survey on weed and crop classi...,2024,Faisal Dharma Adhinata | Wahyono | Raden S...
20,A systematic review of machine learning techni...,2022,Md Ekramul Hossain | Muhammad Ashad Kabir | ...
21,Machine learning in nutrient management: A review,2023,Oumnia Ennaji | Leonardus Vergütz | Achraf ...
22,Deep convolutional neural network models for w...,2022,A. Subeesh | S. Bhole | K. Singh | N.S. Ch...
23,A review on computer vision systems in monitor...,2020,Cedric Okinda | Innocent Nyalala | Tchalla ...
24,Explainable artificial intelligence and interp...,2022,Masahiro Ryo